baseURL = 'https://note.xka.io'
languageCode = 'zh-cn'
title = 'Notebook'
theme = "whiteplain"
disqusShortname = "example"

copyright = "&copy; Copyright 2024 fe1fan"

[params.author]
name = "Fe1Fan"
# Gravatar or Abatar image
gravatar = "Gravatar email or MD5 Hash"
#avatar = "/path/to/avatar"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# Header Menu
[[menu.main]]
name = "Categories"
identifier = "categories"
url = "/categories/"
weight = 1
[[menu.main]]
name = "Series"
identifier = "series"
url = "/series/"
weight = 2
[[menu.main]]
name = "Tags"
identifier = "tags"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 4
[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"
weight = 5

# Footer Menu
[[menu.footer]]
name = "About"
weight = 1
identifier = "about"
url = "/about/"